### ISSUE TITLE
Checkout path should be used rather than working directory

### ISSUE THREAD

**Issue by ghost** [circleci/local-cli#24]
When a configuration defines a checkout operation with a path, and the working_directory is deeper into the path, the build works when actually deployed but breaks locally. 

I have a configuration that defines a test similar to: 
```
service-test:
    docker:
      - image: circleci/node:8.11.1
    working_directory: /home/long/subdir/list/service
    steps: 
      - checkout:
          path: /home/
      - run: npm install
      - run: npm test
```

Actual usage of the test is fine, but when I attempt to use the local-cli the following copy operation is performed for 'checkout':

```
====>> Checkout code
  #!/bin/sh
mkdir -p /home/long/subdir/list/service && cp -r /tmp/_circleci_local_build_repo/. /home/long/subdir/list/service
```

### What is expected
I would expect the checkout directory to be respected in the event the working directory is further into the path and have a shell checkout closer to:
```
#!/bin/sh
mkdir -p /home/ && cp -r /tmp/_circleci_local_build_repo/. /home/ && \
cd home/long/subdir/list/service
```
