### ISSUE TITLE
Checkout: Permission denied

### ISSUE THREAD

**Issue by olback** [circleci/local-cli#25]
I'm having truble chekcking out files when using a node image. Looks like I don't have read permissions in /tmp/. I have no idea if this is an issue with the Circle CI CLI at all or if it's image specific. I tried using `circleci/node:10.0.0` but it didn't help.

```terminal
====>> Checkout code
  #!/bin/sh
mkdir -p /home/circleci/project && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/project
cp: cannot open '/tmp/_circleci_local_build_repo/./target/debug/incremental/olback_net-x3n34a75hw3w/s-f27brgxx5h-tbo2de.lock' for reading: Permission denied
cp: cannot open '/tmp/_circleci_local_build_repo/./target/debug/incremental/olback_net-44sz4ldc4h4b/s-f30zvxqykx-6jqgfl.lock' for reading: Permission denied
cp: cannot open '/tmp/_circleci_local_build_repo/./target/debug/incremental/olback_net-1e1p4liljtgb7/s-f27i8gin8w-1xq36vp.lock' for reading: Permission denied
Error: Exited with code 1
```

Relevant part of my `.circleci/config.yml` file.
```yaml
jobs:
  lint:
    docker:
      - image: circleci/node:8.9.0

    steps:
      - checkout # this is where it fails...

      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}

      - run:
          name: Install node packages
          command: npm install
```
Here's a link to the whole `config.yml` file if it's to any help: [https://github.com/olback/olback.net/blob/3.0/.circleci/config.yml](https://github.com/olback/olback.net/blob/3.0/.circleci/config.yml)
