### ISSUE TITLE
Checkout failure due to missing starting point of `cp`

### ISSUE THREAD

**Issue by tommynovember7** [circleci/local-cli#38]
I'm trying to run a build task with CLI on macOS but, unfortunately, I've faced with the followings:
```
$ circleci build
Docker image digest: sha256:525c91e01875050fbf65cdb4bc83a45744c54f9027fa05f76f88713f3d37f4e3
====>> Spin up Environment
Build-agent version 0.0.7725-9681bc36 (2018-08-09T15:10:50+0000)
Starting container circleci/buildpack-deps:latest-dind
  using image circleci/buildpack-deps@sha256:f9dea38e6583c663bbe2d950b8c9abdb771f9dd587fdb18460da2f4253c3a70a

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1534833691
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=feature/ci-upgrade
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:***
  CIRCLE_SHA1=*******************
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1534833691
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/project && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/project
cp: cannot stat '/tmp/_circleci_local_build_repo/.': No such file or directory
Error: Exited with code 1
Step failed
```

I believe I'm using the latest version.
```
$ circleci version
0.1.1418+de70cdc
```

My `.circleci/config.yml` is absolutely simple for now, but always failed to run.
```
version: 2
jobs:
  build:
    machine:
      enabled: true

    working_directory: ~/project

    environment:
      SYMFONY__AWS__KEY: ****
      SYMFONY__AWS__SECRET: ****

    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            pip install --upgrade pip
            pip install docker-compose
```

I'm not sure it is an issue about `local-cli` or the docker image. Should I go to  https://github.com/CircleCI-Public/example-images?
